services:
  web:
    build: .
    ports:
      - "80:4173"
    restart: unless-stopped
    volumes:
      - sfb_data:/data
    environment:
      - VITE_JETBOOK_BASE_URL=https://seafunboat.seabook.pro
      - VITE_JETBOOK_API_KEY=
      - ADMIN_PASS=sfb2025

volumes:
  sfb_data:
